### ISSUE TITLE
Support deno ?

### ISSUE THREAD

**Issue by luaneyed** [9oelM/simplerecon#1]
How about just `deno run ~~~` without any installation?
I suggest deno because this repository is only dependent on TypeScript and deno supports TypeScript out of the box.

**Comment by 9oelM** [comment]
actually I use `ts-node simplerecon.ts example.com` lol but I can make it work with deno because it's cool and people won't have to clone the repo. I will work on that

**Comment by 9oelM** [comment]
Closing because I converted it to a bash shell script
